### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by yandexman** [RagedUnicorn/wow-pvpwarn#1] opened 2018-09-26 11:20 UTC
Hello

When i type /pvpw opt and click on any class or Racial, items etc i get this lua error

https://cdn.discordapp.com/attachments/408073469004218394/494468065262829568/pvp.png

Addon is not working for me :(

**Comment by yandexman** [comment] 2018-09-26 11:25
Also i disabled all addons and i still get this error

**Comment by RagedUnicorn** [comment] 2018-10-21 22:06
Hi,
Thanks for the hint. I was however not able to reproduce your issue. Please note that I'm still developing this addon. It is indeed possible that this issue was present some commit ago but was fixed since then.

Can you maybe try delete the addon settings once? You should be able to find the in the following place:

`[wow-folder]\WTF\Account\[account-name]\[server-name]\[character-name]\SavedVariables`

And also in:

`[wow-folder]\WTF\Account\[account-name]\[server-name]\SavedVariables`

Make sure to delete both `PVPWarn.lua` and `PVPWarn.lua.bak`

Note this will delete your settings for the addon. If this does not work you can try downloading the newest version.

Regards,
RagedUnicorn

**Comment by RagedUnicorn** [comment] 2018-11-09 08:56
Hi,

I will close this for now. If you are still able to reproduce this issue feel free the reopen the issue.

Regards,
RagedUnicorn

**Closed as completed by RagedUnicorn** 2018-11-09 08:56 UTC
