### ISSUE TITLE
conflicts

### ISSUE THREAD

**Issue by shikulja** [RagedUnicorn/wow-pvpwarn#4] opened 2019-08-08 08:43 UTC
conflicts with ace2 in package !libs
(either AceComm-2 or AceOO-2.0)
![WoWScrnShot_080819_114024_cr](https://user-images.githubusercontent.com/3386359/62688452-890aca80-b9d1-11e9-8208-77938d08b994.png)

https://github.com/laytya/Libs2
https://github.com/laytya/Ace2

and with other add-ons using built-in libraries, the same.

**Comment by shikulja** [comment] 2019-08-10 21:28
I tried to add Russian, but due to an error, it didn’t work. Maybe useful to someone
[PVPWarn rus.zip](https://github.com/RagedUnicorn/wow-vanilla-pvpwarn/files/3506564/PVPWarn.rus.zip)

**Comment by RagedUnicorn** [comment] 2019-08-18 21:51
Hi I'm not sure if I can follow. What makes you think that it is conflicting with ace or any other libraries?

Cheers,
RagedUnicorn

**Comment by shikulja** [comment] 2019-08-19 22:08
> Hi I'm not sure if I can follow. What makes you think that it is conflicting with ace or any other libraries?
> 
> Cheers,
> RagedUnicorn

I'm not sure either. therefore, added LUA, with the translation, after which an error began to occur. maybe someone will figure it out. who knows the code better than me.

**Comment by RagedUnicorn** [comment] 2019-08-23 20:04
Hi Not sure what exactly you changed but I can tell you that the error that happens has to do with the 2 tabs that you can see on your screenshot. I am going to close this however because this seems to be something caused by the changes you did to the addon.

Cheers,
RagedUnicorn

**Closed as completed by RagedUnicorn** 2019-08-23 20:04 UTC
